// Docs Generator - Standalone API Documentation Service
// Generates dynamic HTML documentation from YAML specification files.
//
// Subcommands:
//   docs-gen                       start the HTTP server (default)
//   docs-gen serve [flags...]      explicit server mode
//   docs-gen validate <path>       load and verify a spec, exit 1 on failure
//   docs-gen init [dir]            scaffold a minimal spec/ directory
//   docs-gen prompt                print AGENTS.md to stdout (for AI agents)
//go:generate cp ../../AGENTS.md agents.md

package main

import (
	_ "embed"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"strings"

	"docs-generator/pkg/docs"

	"github.com/gin-gonic/gin"
)

// agentsPrompt is the AGENTS.md content embedded into the binary so that
// `docs-gen prompt` works even in sandboxed environments without filesystem
// or network access. Regenerated by `go generate ./cmd/server` (copies the
// canonical file from the repo root).
//
//go:embed agents.md
var agentsPrompt string

func main() {
	// Route into subcommands when the first non-flag arg matches a known name.
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "validate":
			os.Exit(runValidate(os.Args[2:]))
		case "lint":
			os.Exit(runLint(os.Args[2:]))
		case "init":
			os.Exit(runInit(os.Args[2:]))
		case "prompt":
			os.Exit(runPrompt())
		case "serve":
			os.Args = append([]string{os.Args[0]}, os.Args[2:]...)
		case "-h", "--help", "help":
			printUsage(os.Stderr)
			return
		}
	}
	runServe()
}

func printUsage(w *os.File) {
	fmt.Fprintln(w, "usage:")
	fmt.Fprintln(w, "  docs-gen                       start the HTTP server (default)")
	fmt.Fprintln(w, "  docs-gen serve [flags...]      explicit server mode")
	fmt.Fprintln(w, "  docs-gen validate <path>       parse + JSON-Schema check, exit 1 on failure")
	fmt.Fprintln(w, "  docs-gen lint <path>           semantic checks (dup ids, dangling refs, …)")
	fmt.Fprintln(w, "  docs-gen init [dir]            scaffold spec/ with a minimal example")
	fmt.Fprintln(w, "  docs-gen prompt                print AGENTS.md to stdout (AI agent instructions)")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "flags (for serve):")
	fmt.Fprintln(w, "  -spec, -port, -prefix, -dev, -log-format")
}

// runPrompt prints the embedded AGENTS.md to stdout. Lets AI assistants
// working in sandboxed environments pipe the canonical authoring guide
// directly into their context without a network round-trip.
func runPrompt() int {
	fmt.Println(agentsPrompt)
	return 0
}

func runServe() {
	var (
		specPath  = flag.String("spec", "./spec/index.yaml", "Path to spec file or directory (YAML native or OpenAPI 3.x)")
		port      = flag.String("port", "8080", "Server port")
		prefix    = flag.String("prefix", "/docs", "URL prefix for documentation routes")
		devMode   = flag.Bool("dev", false, "Development mode (hot-reload)")
		logFormat = flag.String("log-format", defaultLogFormat(), "Log format: text or json")
	)
	flag.Parse()

	setupLogging(*logFormat)

	*prefix = "/" + strings.Trim(*prefix, "/")

	if os.Getenv("GIN_MODE") == "" {
		gin.SetMode(gin.ReleaseMode)
	}

	printBanner(*specPath, *devMode, *prefix, *port)

	handler, err := docs.NewHandler(*specPath, *devMode)
	if err != nil {
		slog.Error("failed to initialize docs handler", "err", err)
		os.Exit(1)
	}

	router := gin.Default()

	router.Use(func(c *gin.Context) {
		c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, PATCH, PUT, DELETE, OPTIONS")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}
		c.Next()
	})

	handler.RegisterRoutes(router, *prefix)

	// Expose the AI agent authoring guide so assistants in other projects
	// can fetch it via HTTP without cloning this repo.
	router.GET(*prefix+"/agents", func(c *gin.Context) {
		c.Data(200, "text/markdown; charset=utf-8", []byte(agentsPrompt))
	})

	router.GET(*prefix+"/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":    "ok",
			"service":   "docs-generator",
			"dev_mode":  *devMode,
			"spec_path": *specPath,
		})
	})

	slog.Info("server starting", "port", *port, "prefix", *prefix, "dev", *devMode)
	if err := router.Run(":" + *port); err != nil {
		slog.Error("server stopped with error", "err", err)
		os.Exit(1)
	}
}

// runValidate loads a spec and reports problems without starting the server.
// Two layers:
//   1. Parse + merge (same load path as production) — catches YAML / type errors.
//   2. JSON Schema validation — catches unknown fields, wrong enum values, etc.
//
// Returns the process exit code.
func runValidate(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: docs-gen validate <path-to-spec>")
		return 2
	}
	path := args[0]

	if _, err := docs.NewHandler(path, false); err != nil {
		fmt.Fprintf(os.Stderr, "invalid: %v\n", err)
		return 1
	}

	if errs := docs.ValidateFile(path); len(errs) > 0 {
		fmt.Fprintf(os.Stderr, "invalid (%d schema violation(s)):\n", len(errs))
		for _, e := range errs {
			fmt.Fprintf(os.Stderr, "  %s\n", e.Error())
		}
		return 1
	}

	fmt.Fprintf(os.Stderr, "ok: %s\n", path)
	return 0
}

// runLint runs semantic checks (duplicate ids, dangling anchors, permission
// reference orphans, auth-label drift, empty descriptions). Errors exit 1;
// warnings exit 0 — use -strict to treat warnings as errors.
func runLint(args []string) int {
	fs := flag.NewFlagSet("lint", flag.ExitOnError)
	strict := fs.Bool("strict", false, "Treat warnings as errors (CI-friendly)")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	rest := fs.Args()
	if len(rest) == 0 {
		fmt.Fprintln(os.Stderr, "usage: docs-gen lint [-strict] <path-to-spec>")
		return 2
	}
	path := rest[0]

	diags := docs.LintFile(path)
	if len(diags) == 0 {
		fmt.Fprintf(os.Stderr, "clean: %s\n", path)
		return 0
	}

	errors, warnings := 0, 0
	for _, d := range diags {
		fmt.Fprintln(os.Stderr, d.String())
		if d.Severity == docs.SeverityError {
			errors++
		} else {
			warnings++
		}
	}
	fmt.Fprintf(os.Stderr, "— %d error(s), %d warning(s)\n", errors, warnings)
	if errors > 0 || (*strict && warnings > 0) {
		return 1
	}
	return 0
}

// runInit scaffolds a minimal spec directory that a new user can edit.
func runInit(args []string) int {
	target := "spec"
	if len(args) > 0 {
		target = args[0]
	}
	if _, err := os.Stat(target); err == nil {
		fmt.Fprintf(os.Stderr, "refuse to overwrite existing path: %s\n", target)
		return 1
	}
	if err := os.MkdirAll(target, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", target, err)
		return 1
	}
	if err := os.WriteFile(target+"/index.yaml", []byte(scaffoldYAML), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		return 1
	}
	fmt.Fprintf(os.Stderr, "scaffolded %s/index.yaml\n", target)
	fmt.Fprintf(os.Stderr, "run: docs-gen -spec %s/index.yaml\n", target)
	return 0
}

const scaffoldYAML = `# yaml-language-server: $schema=https://raw.githubusercontent.com/Go-Routine-App/go-docs-generator/main/schemas/spec.schema.json
info:
  title: My API
  version: "1.0.0"
  description: Describe your API here.
  base_urls:
    - label: Production
      url: https://api.example.com
      default: true
    - label: Staging
      url: https://staging.api.example.com

authentication:
  methods:
    - type: Bearer JWT
      header: Authorization
      format: "Bearer <token>"
      description: Standard bearer token authentication.

sections:
  - id: hello
    title: Hello
    description: A sample section — replace with your own.
    endpoints:
      - name: Ping
        method: GET
        path: /ping
        auth: none
        description: Liveness check.
`

// setupLogging configures slog with the requested handler.
func setupLogging(format string) {
	level := slog.LevelInfo
	if lv := os.Getenv("LOG_LEVEL"); lv != "" {
		switch strings.ToLower(lv) {
		case "debug":
			level = slog.LevelDebug
		case "warn":
			level = slog.LevelWarn
		case "error":
			level = slog.LevelError
		}
	}
	opts := &slog.HandlerOptions{Level: level}
	var h slog.Handler
	if strings.EqualFold(format, "json") {
		h = slog.NewJSONHandler(os.Stderr, opts)
	} else {
		h = slog.NewTextHandler(os.Stderr, opts)
	}
	slog.SetDefault(slog.New(h))
}

func defaultLogFormat() string {
	if os.Getenv("GIN_MODE") == "release" || os.Getenv("LOG_FORMAT") == "json" {
		return "json"
	}
	return "text"
}

func printBanner(specPath string, devMode bool, prefix, port string) {
	fmt.Fprintln(os.Stderr, "Docs Generator")
	fmt.Fprintln(os.Stderr, "===========================================")
	fmt.Fprintf(os.Stderr, "Spec:   %s\n", specPath)
	fmt.Fprintf(os.Stderr, "Dev:    %v\n", devMode)
	fmt.Fprintf(os.Stderr, "Prefix: %s\n", prefix)
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "Endpoints:")
	fmt.Fprintf(os.Stderr, "  http://localhost:%s%s\n", port, prefix)
	fmt.Fprintf(os.Stderr, "  http://localhost:%s%s/spec\n", port, prefix)
	fmt.Fprintf(os.Stderr, "  http://localhost:%s%s/specs\n", port, prefix)
	fmt.Fprintf(os.Stderr, "  http://localhost:%s%s/yaml\n", port, prefix)
	fmt.Fprintf(os.Stderr, "  http://localhost:%s%s/openapi\n", port, prefix)
	fmt.Fprintf(os.Stderr, "  http://localhost:%s%s/agents\n", port, prefix)
	fmt.Fprintf(os.Stderr, "  http://localhost:%s%s/health\n", port, prefix)
	fmt.Fprintln(os.Stderr, "")
}
